### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by Natsusai** [lyq1996/supplicant#4]
之前没问题，今天校园网有一段时间无法上网（维护？），过后脚本无法连接，学校给的安朗客户端正常工作

错误如下
Traceback (most recent call last):
  File "E:\Tool\校园网\supplicant-master\supplicant0.1.3.py", line 181, in <module>
    main()
  File "E:\Tool\校园网\supplicant-master\supplicant0.1.3.py", line 177, in main
    session = login(sock, upnet_packet ,message_display)
  File "E:\Tool\校园网\supplicant-master\supplicant0.1.3.py", line 24, in login
    response = sock.recv(3848)
socket.timeout: timed out

另一错误是
Traceback (most recent call last):
  File "E:\Tool\校园网\supplicant-master\supplicant0.1.3.py", line 181, in <module>
    main()
  File "E:\Tool\校园网\supplicant-master\supplicant0.1.3.py", line 177, in main
    session = login(sock, upnet_packet ,message_display)
  File "E:\Tool\校园网\supplicant-master\supplicant0.1.3.py", line 30, in login
    message_len = response[response.index(11,35)+1]
ValueError: 11 is not in list

**Comment by Natsusai** [comment]
开看来只是电信那边的问题。。。。

**Comment by lyq1996** [comment]
现在正常了就好...那个一般是因为服务器没回应..跟你应该没关系
